export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Use Inter + JetBrains Mono for a modern, technical look */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=JetBrains+Mono:ital,wght@0,400;0,700&display=swap" rel="stylesheet" />
      </head>
      <body className="min-h-screen bg-gradient-to-b from-gray-50 to-white dark:from-gray-900 dark:to-gray-800 font-sans">
        <div className="max-w-5xl mx-auto px-4 py-8">
          <header className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 flex items-center justify-center rounded-lg bg-gradient-to-br from-indigo-600 to-cyan-500 text-white shadow-lg">
                {/* simple server rack / cloud svg */}
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M3 7h18v4H3z" fill="currentColor" opacity="0.9"/>
                  <path d="M5 13h14v6H5z" fill="currentColor" opacity="0.7"/>
                </svg>
              </div>
              <div>
                <h1 className="text-2xl font-semibold">Infrastructure Cost Calculator</h1>
                <p className="text-sm text-gray-500 dark:text-gray-300">Compare cloud, Kubernetes and on-prem costs instantly</p>
              </div>
            </div>
            <div className="text-sm text-gray-600 dark:text-gray-300">v1.0 • Demo</div>
          </header>

          <main className="bg-white dark:bg-gray-700 shadow-md rounded-lg p-6">{children}</main>
        </div>
      </body>
    </html>
  )
}
